name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Run tests
        uses: handy-common-utils/automation/github/actions/ci-node@main
        with:
          node-version: ${{ matrix.node-version }}
